#config view resolverspring:
spring:
  mvc:
    view:
      prefix: /templates/
    static-path-pattern: /static/**
#config datasource(mysql)
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql:///springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Tian@543845
#config druid
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
  # config file upload
  http:
    multipart:
      # one file
      maxFileSize: 1048576
      # all file
      maxRequestSize: 10485760
    # config character encoding
    encoding:
      charset: UTF-8
      force: true
      enabled: true
# config mybatist xml
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tian.test.entity
  # config server port
server:
  port: 8888
